# Generated by Django 2.0.6 on 2018-10-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
