# Generated by Django 2.0.6 on 2018-09-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='add_product',
        ),
    ]
