# Generated by Django 2.0.6 on 2018-09-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_product_linkpdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='linkpdf',
        ),
    ]
