# Generated by Django 2.0.6 on 2018-10-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_product_linkpdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='linkpdf',
        ),
        migrations.AddField(
            model_name='add_product',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
